import { createMuiTheme, responsiveFontSizes } from '@material-ui/core';

const theme = createMuiTheme({
  typography: {
    h1: {
      fontSize: '3.5rem',
      fontFamily: [
        'mr-eaves-xl-modern',
        '-apple-system',
        'BlinkMacSystemFont',
        'Segoe UI',
        'Roboto',
        'Oxygen',
        'Ubuntu',
        'Cantarell',
        'Fira Sans',
        'Droid Sans',
        'Helvetica Neue',
        'sans-serif',
      ].join(','),
      fontWeight: 'bold',
      lineHeight: '1.1',
    },
    h2: {
      fontSize: '2.375rem',
      fontFamily: [
        'mr-eaves-xl-modern',
        '-apple-system',
        'BlinkMacSystemFont',
        'Segoe UI',
        'Roboto',
        'Oxygen',
        'Ubuntu',
        'Cantarell',
        'Fira Sans',
        'Droid Sans',
        'Helvetica Neue',
        'sans-serif',
      ].join(','),
      fontWeight: 'bold',
    },
    h3: {
      fontSize: '2rem',
      fontFamily: [
        'mr-eaves-xl-modern',
        '-apple-system',
        'BlinkMacSystemFont',
        'Segoe UI',
        'Roboto',
        'Oxygen',
        'Ubuntu',
        'Cantarell',
        'Fira Sans',
        'Droid Sans',
        'Helvetica Neue',
        'sans-serif',
      ].join(','),
      fontWeight: 'bold',
    },
    h4: {
      fontSize: '1.5625rem',
      fontFamily: [
        'mr-eaves-xl-modern',
        '-apple-system',
        'BlinkMacSystemFont',
        'Segoe UI',
        'Roboto',
        'Oxygen',
        'Ubuntu',
        'Cantarell',
        'Fira Sans',
        'Droid Sans',
        'Helvetica Neue',
        'sans-serif',
      ].join(','),
      fontWeight: 'bold',
    },
    h5: {
      fontSize: '1.25rem',
      fontFamily: [
        'mr-eaves-xl-modern',
        '-apple-system',
        'BlinkMacSystemFont',
        'Segoe UI',
        'Roboto',
        'Oxygen',
        'Ubuntu',
        'Cantarell',
        'Fira Sans',
        'Droid Sans',
        'Helvetica Neue',
        'sans-serif',
      ].join(','),
      fontWeight: 'bold',
    },
    h6: {
      fontSize: '1.125rem',
      fontFamily: [
        'mr-eaves-xl-modern',
        '-apple-system',
        'BlinkMacSystemFont',
        'Segoe UI',
        'Roboto',
        'Oxygen',
        'Ubuntu',
        'Cantarell',
        'Fira Sans',
        'Droid Sans',
        'Helvetica Neue',
        'sans-serif',
      ].join(','),
      fontWeight: 'bold',
    },
  },
});

export default responsiveFontSizes(theme);
